# Generated by Django 5.1.7 on 2025-03-18 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parqueadero',
            old_name='ubicaccion',
            new_name='ubicacion',
        ),
    ]
